theme: jekyll-theme-cayman
title: Contrat logiciel de don solidaire
description : Expérimentation en cours : des donateurs versent des dons directs à des bénéficiaires de l'allocation adulte handicapé
